# Generated by Django 4.0.1 on 2022-04-18 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BluetoothDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texting_timeout', models.IntegerField()),
                ('update_journey_interval', models.IntegerField()),
                ('bluetooth_in_range', models.ManyToManyField(to='manage_device.BluetoothDevice')),
                ('journeys', models.ManyToManyField(to='tracker.Journey')),
                ('registeredBluetoothDevices', models.ManyToManyField(related_name='registeredBluetoothDevices', to='manage_device.BluetoothDevice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
